#!/bin/bash
echo"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl nulla. Aliquam erat volutpat. Integer ullamcorper nisi massa, non laoreet nisl vestibulum nec. Donec sodales lacus lorem, sit amet vehicula sem lacinia eget. Suspendisse potenti. Fusce ut blandit nulla, sit amet pharetra urna"
